version: '3.9'

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: my_db
    image: postgres:14.3-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com 
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  web-market:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: web-market
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: bash -c "sleep 10 && backend/manage.py migrate && backend/manage.py shell < backend/create_superuser_script.py && backend/manage.py runserver 0.0.0.0:8000"

    
