# Generated by Django 4.2.5 on 2024-02-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0002_remove_product_freedelivery_product_free_delivery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                related_name="tags", to="shopapp.tag", verbose_name="Тег"
            ),
        ),
    ]
