# Generated by Django 4.2.5 on 2024-02-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0006_alter_order_basket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="delivery_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="full_name",
            new_name="customer",
        ),
    ]
